### PR TITLE
Install pystan in base analytics image

### PR DESCRIPTION
**Pull request by erikbern**
Another library that is super slow (5-10 minutes) to install.

### CODE REVIEW

**Comment by imsky** [comment]
👍

**Comment by erikbern** [comment]
Thanks

A bit nervous we're close to the 2h build timeout on Dockerhub... let's see if it works

**Comment by erikbern** [comment]
This actually crashes when I run it locally... 🤔

**Comment by erikbern** [comment]
Works in Buildkite though. I'll merge and see what happens, can revert later.

**Pull request merged**
