### PR TITLE
fix redshift cert location

### PR DESCRIPTION
**Pull request by imsky**

### CODE REVIEW

**Comment by alikhan-io** [comment]
lgtm

**Review by alikhan-io — APPROVED** [review]

**Comment by imsky** [comment]
thanks @alikhan-io

**Review by docimou — COMMENTED** [review]
do we not need to cp to /etc/ssl as in the run command for the rds cert here?

**Comment by imsky** [comment]
no @docimou - /etc/ssl is usually (but not always) a user-managed SSL cert directory. here we're adding a CA cert

**Pull request merged**
