### PR TITLE
adding pandas to analytics image

### PR DESCRIPTION
**Pull request by stphnma**

### CODE REVIEW

**Comment by imsky** [comment]
:shipit: 

make sure to re-push the analytics tag once build is done

**Comment by erikbern** [comment]
> make sure to re-push the analytics tag once build is done

what does this mean? can you document?

**Comment by imsky** [comment]
i sent more details to Stephen via DM:

    once this build finishes https://hub.docker.com/r/better/baseimage/builds/bzdeglanmutowh8dsdcrqwm/
    merge your PR
    then make sure you have latest on your local
    then run `git push origin :analytics-alpine-3.7` which will delete the git tag
    then run `git tag analytics-alpine-3.7` and `git push origin master --tags` to kick off the master build

**Comment by erikbern** [comment]
can you put that in the README.md?

**Comment by imsky** [comment]
sure

**Comment by alikhan-io** [comment]
Could we not have BuildKite watch this repo and just do it automatically?

**Comment by imsky** [comment]
@alikhan-io CI is set up via Docker Hub, not Buildkite

**Pull request merged**
